### ISSUE TITLE
Best way to cite Tudat/Tudatpy?

### ISSUE THREAD

**Issue by astrojuanlu** [tudat-team/tudat#103]
Hi! I'm writing a conference paper on [poliastro](https://github.com/poliastro/poliastro/), an open-source Python library for interactive Astrodynamics (WIP draft [here](https://github.com/scipy-conference/scipy_proceedings)) and I just remembered that tudat exists (thanks @nosudrum!). What would be the best way to cite it in an academic piece of work? I see that [lots of research uses Tudat](https://docs.tudat.space/en/stable/_src_about/about.html), but I don't see a "proper citation" anywhere.

In case there isn't, I will figure out a way to generate a proper BiBTeX fragment from this repository or the tudatpy one. (And also in that case you should check out https://zenodo.org/ and https://joss.theoj.org/!)

**Comment by Nosudrum** [comment]
I was going to ask the same question within the next few weeks, so I'm definitely interested in the answer :)

**Comment by DominicDirkx** [comment]
Hi Juan, great to hear that you want to incorporate a mention of Tudat in your work! If you've used Tudat(py) and have any input for us, we're very open to hearing outside opinions, advice, criticisms, etc. Now that wee have a decently working Python interface, and not just a C++ interface, we'll be doing a lot more over the coming year to making Tudat known to people outside of our Spaceflight M.Sc. curriculum.

At the moment, there is not a very good way to cite Tudat, _but_:
* We will be getting some support from the TU Delft 'Center for Digital Competencies', and making Tudat citable one of the things thy will support us with. We have the kickoff of this support next week, and I hope to be able to update you on this soon
* We will have a presentation/poster at both IAC (https://iac2022.org/) and EPSC (https://www.epsc2022.eu/) in September (for IAC, there is also an accompanying paper)
* There is an Appendix on Tudat in this semi-recent paper: https://link.springer.com/article/10.1007/s10509-019-3521-4 It's by no means the ideal way to cite Tudat, though...
* The 'place to go' for someone unfamiliar with Tudat is https://docs.tudat.space/ with the code being here: https://github.com/tudat-team. I'll leave it to you to choose which one(s) best fit the paper you're working on 

If you need any more info, don't hesitate to let us know,

Dominic

**Comment by DominicDirkx** [comment]
Thanks for putting us in there. If at any time in the future you'd be interested in diving into Tudat and want to have a chat about it, our door is open :)

**Comment by Nosudrum** [comment]
Hi @DominicDirkx
> We have the kickoff of this support next week, and I hope to be able to update you on this soon

do you have any news on this ?

> We will have a presentation/poster at IAC (https://iac2022.org/)

Do you already have more info on this (date & location of presentation) ? I suppose the poster will be at the TU Delft booth ?

**Comment by DominicDirkx** [comment]
Apologies, I missed your message. The DCC kickoff got postponed due to illness, unfortunately. I hope to update you soon. I'm not sure which session we're in for the IAC. We have a presentation in one of the regular sessions, @transferorbit and @FilippoOggionni may know more.

**Comment by transferorbit** [comment]
The most recent information I have is that we are scheduled for an _Interactive Presentation_ on 21 Sep 2022. We will only be notified of the time-slot and screen number in August.

**Comment by DominicDirkx** [comment]
Do you know if the abstract is already available on the IAC website?
