### ISSUE TITLE
Cumulative number of function evaluations history

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#105]
Hi all.
The cumulative_number_of_function_evaluations attribute from the SingleArcSimulator does not return the number of function evaluations at each time step as it states in the [API](https://py.api.tudat.space/en/latest/numerical_simulation.html#tudatpy.numerical_simulation.SingleArcSimulator). Instead, it returns a time history with the time for all function evaluations (so multiple epochs per time step) and the function evaluations for each of those, meaning that currently the number of functions evaluations can actually oscillate as the time increases (see [code](https://github.com/tudat-team/tudat/blob/9a02a32ac5546dbe51b83cc1616f2480f9776cfc/include/tudat/astro/propagators/dynamicsStateDerivativeModel.h#L243-L245)). This also means that the time history associated with the number of functions evaluations does not coincide with the time history associated e.g. with the state history.

This behavior should be clarified in the API, or ideally, the code changed to only return the number of functions evaluations at the end of each time step.

**Comment by DominicDirkx** [comment]
These docstrings have been reorganized and updated in this branch:
https://github.com/tudat-team/tudat-multidoc/tree/feature/consistent_propagation_settings
which will be merged soon
