### ISSUE TITLE
Acceleration partials as dependent variables: error checking, misleading names

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#106]
When computing the acceleration partials as dependent variables the `getAccelerationPartialForBody` function is called. This function checks for the correct acceleration partial, and sets the boolean `partialIdentified` to true if it found it (see [here](https://github.com/tudat-team/tudat/blob/ec15c619ab1c723ef27a441b001748f629d1620c/src/astro/propagators/dynamicsStateDerivativeModel.cpp#L14-L67)); however, it is never checked whether `partialIdentified` is False at the end of the function.

For 3rd body accelerations, the `AccelerationPartialWrtStateSaveSettings` class has as argument the name of the 3rd body (see [here](https://github.com/tudat-team/tudat/blob/ec15c619ab1c723ef27a441b001748f629d1620c/include/tudat/simulation/propagation_setup/propagationOutputSettings.h#L475)). However, that argument should be the central body, not the 3rd body, as can be seen by the call to [this](https://github.com/tudat-team/tudat/blob/ec15c619ab1c723ef27a441b001748f629d1620c/src/astro/propagators/dynamicsStateDerivativeModel.cpp#L14-L19) function done [here](https://github.com/tudat-team/tudat/blob/ec15c619ab1c723ef27a441b001748f629d1620c/include/tudat/simulation/propagation_setup/propagationOutput.h#L1141-L1146).

Also, it would be nice to have a dependent variable corresponding to the full acceleration partials, instead of just each individual contribution to the acceleration partials.

**Comment by DominicDirkx** [comment]
I'm assigning this to @MarieFayolle, who is also using this in the context of observation partial calculations. @MarieFayolle, could you check if the changes proposed my Miguel would have an impact on your functionality?

**Comment by MarieFayolle** [comment]
Hi Dominic, Miguel,
I completely agree with the changes proposed by Miguel and it won't affect anything on my side. 
@MiguelAvillez  About your last point (full acceleration partials), I have this already implemented on a local branch and I was just having a look at it yesterday actually :) I originally added this to an older version of Tudat but I was planning to push these changes to the actual tudat code in the coming weeks

**Comment by MiguelAvillez** [comment]
Just a small addition: right now when selecting a 3rd body acceleration partial it is necessary to specify the acceleration as actually being a 3rd body acceleration; it would be nice to also be able to  just specify the direct acceleration type (similarly to what happens when retrieving accelerations as dependent variables)

**Comment by DominicDirkx** [comment]
I'm finally making some time to go through this, I hope to be able to make a preliminary push by the end of the day

@MarieFayolle, could you share a link to the branch where you have the full partial implemented? I can move it into the develop tudat branch

**Comment by MarieFayolle** [comment]
@DominicDirkx I think that you can find it here on this branch: https://github.com/MarieFayolle/tudat-1/commits/extendedOrbitDeterminationModule
But this is a (very very) old version of Tudat, so I am not sure how useful it is for you. Do you need me to move these features to the newest version?

**Comment by DominicDirkx** [comment]
I've moved the code (inlcuding unit test, many thanks!) from @MarieFayolle 's code to the new Tudat version, and have opened a pull request:
https://github.com/tudat-team/tudat/pull/124
Most of the updates are obvious, one change is that the central body input to the dependent variables is removed. As with the accelerations themselves, this input does not really serve a purpose (?). In a given single-arc simulation, only a single central body for the propagation is possible, and adding this as a check does not change the results. 

One possible exception (which we should then also add in the saving of the 3rd body acceleration, not only the partial), is the following:
* You want to save the acceleration of body B acting on body A, but **only if the central body is C**. At the moment, this is not supported. @MarieFayolle, is this something that is useful/important for your work (or anyone's work?). If so, I suggest we open a new issue requesting this functionality for the saving of both accelerations and acceleration partials

**Comment by MarieFayolle** [comment]
Awesome! I hope that it was not too much of a struggle? I somehow remember this piece of code as very messy. 

Concerning your question, it might be interesting to have this, but I am not sure whether it should be given a high priority for now. Can you think of any test case in which we would absolutely need this? Right now I can't think of any (at least none that would not be solvable with an easy work-around).

**Comment by DominicDirkx** [comment]
Not at all, it was a simple copy paste from a few places, and it all worked fine. One possible use case for the functionality would be, taking the JUICE multi-arc flyby trajectory of multiple moons as an example:
* Save the 3rd body perturbation exerted by Jupiter on JUICE, but only if the flyby body is Europa (e.g. if the flybys is of Europa)
This is a rather niche application, and if you don't need anything like this right now, let's merge this pull request.

**Comment by MarieFayolle** [comment]
yes I thought about this one, but honestly I don't think I really need it right now and I can always do this in post-processing. So you can definitely merge in my opinion :)

**Comment by DominicDirkx** [comment]
Great, code merged :)
