### ISSUE TITLE
New unit test: integrator error vs timestep

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#113]
The order of the integrators implemented in tudat (both fixed and variable step) can be tested using a similar script as the one in the upcoming example discussed in [tudatpy-example#9](https://github.com/tudat-team/tudatpy-examples/issues/9). 

Allowing for some marking of error, the line that results from plotting the error in position vs the timestep of the integrators allows for checking their orders. This may require fine-tuning the number of points plotted in the example so that the unit test uses as few points as possible, with as high time steps as possible (to make the unit test faster, while still accurate).

**Comment by DominicDirkx** [comment]
Resolution of issue will be tracked here: https://github.com/tudat-team/tudat/issues/166
