### ISSUE TITLE
Custom dependent variable bugs

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#114]
In [propagationOutput.cpp](https://github.com/tudat-team/tudat/blob/0fb03c838214ecd666e9f5f69aa3752df3dafcc7/src/simulation/propagation_setup/propagationOutput.cpp#L407-L408) the size of the custom dependent variable is selected as 3*(size specified by the user). That "3*" should be removed.

In [propagationOutput.h](https://github.com/tudat-team/tudat/blob/49be41a985eb3f0f35aef67f41c9ff55f04ffe43/include/tudat/simulation/propagation_setup/propagationOutput.h#L1151) the custom dependent variable is only declared under `getVectorDependentVariableFunction`, therefore when selecting a custom dependent variable with dimension 1 (where `getDoubleDependentVariableFunction ` is called) the propagation is terminated with the error
`Error, did not recognize double dependent variable type when making variable function:`

**Comment by DominicDirkx** [comment]
I added a fix, with unit test, and it all seems to work now. It's been pushed to develop. Thanks for pointing this out!
