### ISSUE TITLE
Polyhedron gravity and shape code

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#117]
Implement polyhedron code:
- [x] Polyhedron gravity
- [x] Propagation of polyhedron variational equations
- [x] Polyhedron shape model
- [x] Retrieving gravity potential and laplacian as dependent variables
- [x] Document all of the above: API
- [x] Document all of the above: user guide

**Comment by MiguelAvillez** [comment]
Branch with tudapy: https://github.com/MiguelAvillez/tudatpy/tree/feature/polyhedron
Branch with tudat: https://github.com/MiguelAvillez/tudat/tree/feature/polyhedron
Branch with API: https://github.com/MiguelAvillez/tudat-multidoc

**Comment by DominicDirkx** [comment]
This looks awesome, thanks! I should be able to have a look at this next week

**Comment by MiguelAvillez** [comment]
Actually the code is not yet completely ready to be merged, I was just posting all the branches here to later avoid forgetting to create pull requests for any of them.
I still need to add some more unit tests and fix something in the dependent variables... I'm getting a segmentation fault :)

**Comment by MiguelAvillez** [comment]
Pull requests:
Tudat: https://github.com/tudat-team/tudat/pull/118
Tudatpy: https://github.com/tudat-team/tudatpy/pull/77
API: https://github.com/tudat-team/tudat-multidoc/pull/52
User guide: https://github.com/tudat-team/tudat-space/pull/75

**Comment by DominicDirkx** [comment]
In the process of merging the pull requests :)

For future reference, below are some suggestions for future extensions (copied from #118):

A couple questions/suggestions for future extensions (none of which need to be done before merging!)

    Do you have code (or literature) to convert the polyhedron to a spherical harmonic field? This would be nice for comparison purposes (among other applications)
    It would be cool if there were a function to load a typical polyhedron files. I'm not sure if the format is typical, but there's a consistent (and huge!) list of polyhedra for asteroids here: https://astro.troja.mff.cuni.cz/projects/damit/asteroids/browse. A loadDamitPolyhedron( ) function would be nice!
    At the moment, the interfaces only allow for providing the vertices and the list of vertices for each trilateral on the polyhedron. The former is a 'fundamental' input, but the latter could be generated automatically (although non-uniquely). For instance, using Dalaunay triangulation (https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html), it seems that this would be fairly straightforward. This functionality may make the usage more flexible, and would also you to more easily 'downsample' the polyhedron.
    Is there a check in the acceleration if the evaluation point is inside the polyhedron? I don't think so. I'm not sure if there has to be, but a note should be made in the acceleration model API docs

**Comment by MiguelAvillez** [comment]
> Do you have code (or literature) to convert the polyhedron to a spherical harmonic field? This would be nice for comparison purposes (among other applications)

I have an example code developed by Bart Root (forwarded to me by Maarten), which uses the GSH package: https://github.com/bartroot/GSH
I haven't actually looked at the code so no idea what it contains, but Maarten has used, so for better questions ask him :)

Just for reference, there are different methods to compute the SH coefficients. One them is presented in https://www.sciencedirect.com/science/article/pii/S0098300497001106 by the original author of the polyhedron model. However, I do remember seeing somewhere that that algorithm induces large numerical errors for high degree and order coefficients

> Is there a check in the acceleration if the evaluation point is inside the polyhedron? I don't think so. I'm not sure if there has to be, but a note should be made in the acceleration model API docs

Nope, there isn't and there shouldn't be. The evaluation of the acceleration is valid inside the polyhedron. Also, evaluating the Laplacian of the acceleration allows determining whether a point is inside or outside the polyhedron, which can be rather useful to detect impacts.
