### ISSUE TITLE
Error in costateBasedThrustGuidance reference frame transformation

### ISSUE THREAD

**Issue by RobertKlavers** [tudat-team/tudat#13]
I ran into an issue where the `costateBasedThrustGuidance` would return different thrust angles than expected.

https://github.com/tudat-team/tudat/blob/fa30c49dca7ee27630717efb8546802589a4c8b7/src/astro/propulsion/costateBasedThrustGuidance.cpp#L94-L98

The thrust angles (α,β) in the guidance law are defined in an RSW-frame whereas they're currently transformed to the inertial frame using the LVLH reference frame. I believe this is wrong and can be fixed by either using the inertial to RSW that is available in `reference_frames`:

```cpp
Eigen::Vector3d currentRSWForceDirection = (Eigen::Vector3d() <<
    sin(thrustAngleAlpha) * cos(thrustAngleBeta),
    cos(thrustAngleAlpha) * cos(thrustAngleBeta),
    sin(thrustAngleBeta)
).finished().normalized();
Eigen::Matrix3d intertialToRswRotMat = reference_frames::getInertialToRswSatelliteCenteredFrameRotationMatrix(currentState);
currentForceDirection_ = intertialToRswRotMat.transpose() * currentRSWForceDirection;
```
or technically also simply by determining the flight-path angle and use that to define α in the LVLH frame. But the former seems the more clean and obvious solution.

The reason that I only noticed this issue now is because I've been working with near-circular orbits, and this error only becomes more pronounced for increasing eccentricty. I also discussed this with Marie.

**Comment by MarieFayolle** [comment]
Yes, we looked into it together with Robert and his fix seems to work perfectly! After modification, it also led to more consistent results when validating against other studies on hybrid low-thrust methods. I think we will need to update the unit tests as well (my best guess is that the current bounds are just slightly too loose).

**Comment by RobertKlavers** [comment]
> Yes, we looked into it together with Robert and his fix seems to work perfectly! After modification, it also led to more consistent results when validating against other studies on hybrid low-thrust methods. I think we will need to update the unit tests as well (my best guess is that the current bounds are just slightly too loose).

To be more specific, my change causes 3 test cases in the `testMeeCostateBasedThrust` to fail, summarized:

|case|test|result|
|----|----|---|
|λ<sub>p</sub> = 100|error g < 0.025 |(was 0.037)|
|λ<sub>f</sub> = 100|error p < 200.03e| (was 626e3)|
|λ<sub>g</sub> = 100|error p < 200.0e3| (was 461e3)| 

If desired I could further elaborate my findings and provide some examples.

https://github.com/tudat-team/tudat/blob/fa30c49dca7ee27630717efb8546802589a4c8b7/tests/src/astro/propulsion/unitTestThrustAcceleration.cpp#L1748-L1945)

**Comment by DominicDirkx** [comment]
Hi Robert, thanks for pointing this out, I quickly discussed this with Marie today, and she concurs that the original reference frame was probably wrong. 

Concerning the now failing unit tests, is this simply a matter of slightly different rounding errors, and are the results still 'good', or is there something more fundamental going on in your opinion?
