### ISSUE TITLE
More explanatory error when using body_settings after generating bodies

### ISSUE THREAD

**Issue by LuisMPena** [tudat-team/tudat#141]
As per the last conversation in the slack, currently when using the body_settings after generating the bodies either does not give a warning, `body_settings.get("Satellite").constant_mass` lets the code run without any warning, or gives a very brief error, `body_settings.get("Satellite").ephemeris` gives `IndexError: map::at` . Could it be possible to add a more explanatory error when this  happens? Thanks a lot!

**Comment by DominicDirkx** [comment]
@LuisMPena, could you link to a script that results in the error you describe?
