### ISSUE TITLE
Tests multi/hybridArcVariationalEquations failing sometimes

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#143]
Running the tests for the develop branch of tudat, the tests 160 (test_propagators_MultiArcVariationalEquations) and 161 (test_propagators_HybridArcVariationalEquations) **sometimes** fail, so I guess there is some undefined behavior going on. Tests were run on macos 13.2. 

Error logs are attached.

[error_test160.txt](https://github.com/tudat-team/tudat/files/10662795/error_test160.txt)
[error_test161.txt](https://github.com/tudat-team/tudat/files/10662796/error_test161.txt)
 
@DominicDirkx Should I assign this to someone (whom?)?

**Comment by DominicDirkx** [comment]
Hi Miguel, very strange... We'll have a look at this in the near future. Could you assign me and Marie?

**Comment by MiguelAvillez** [comment]
Hi Dominic. As requested, I ran the two test in debug mode, the errors are attached. The errors continue to only happen occasionally. 
For the hybrid arcs test the error continues to be
`std::runtime_error: Error, for arc 2 out of 2, body Mars is estimated but not propagated.`
For the multi arcs test the error now is 
`std::runtime_error: Error, for arc 5 out of 10, body Earth is estimated but not propagated.`
(before it was failing for arc 2 out of 10).

[error_test_hybrid_debug.txt](https://github.com/tudat-team/tudat/files/10785484/error_test_hybrid_debug.txt)
[error_test_multi_debug.txt](https://github.com/tudat-team/tudat/files/10785485/error_test_multi_debug.txt)

**Comment by DominicDirkx** [comment]
Can you get a stack trace from the debugger from it?

**Comment by DominicDirkx** [comment]
Fixed!
