### ISSUE TITLE
Vehicle center of mass

### ISSUE THREAD

**Issue by irmakcavdar** [tudat-team/tudat#147]
These are follow up issues from the meeting:
1. It would be very nice if the vehicle center of mass can be a user defined input in Tudat. This would be crucial when there is a shift in center of mass due to reduced fuel mass (propulsion system). Furthermore, it also has would affect the moment coefficients both the body and control surfaces. 
2. The mass dependency could be added to center of mass and inertia tensors.

**Comment by DominicDirkx** [comment]
Thanks :) As discussed, for the first point, please provide the exact equations that you would like implemented, and I'll do my best to get to it ASAP.

**Comment by irmakcavdar** [comment]
Thanks a lot for all the help! :) I will send you the equations ASAP as well, probably bit later today. There is a bit of rush but not too much as currently I am still working on the unpowered vehicle. So the implementation of powered will follow in a week or 10 days. (I wanted to mention just for you to have an overview of the flow for yourself)

**Comment by DominicDirkx** [comment]
For a first implementation, I won't add the automatic mass-dependency of the inertia tensor and center of mass, but will implement:
* A manual interface to set the center of mass (identical conceptually to the inertia tensor)
* An automatic link between the center of mass and the contribution to the aerodynamic moments
I plan on using the following defaults, let me know if you don't think this would be a good idea:
* Default initialization of center of mass  position r_com to (0,0,0)
* Use +/- (which one?) r_com - r_ref (with r_ref the moment reference point) as the moment arm of the force to compute the moment addition
