### ISSUE TITLE
Overwriting Flight Conditions

### ISSUE THREAD

**Issue by irmakcavdar** [tudat-team/tudat#148]
Currently, when a new set of flight conditions are called or created manually, the already existing ones are overwritten. That should not be the case so this might need to be fixed, and perhaps an error message could be added.

**Comment by DominicDirkx** [comment]
Code fixed in this commit to develop:
https://github.com/tudat-team/tudat/commit/97573b41d3069ff9698b0efa48a1f535b7443082
