### ISSUE TITLE
Integrator does not invalidate timestep that overshoots valid parameter range (i.e., reaching NaN)

### ISSUE THREAD

**Issue by briha** [tudat-team/tudat#155]
When the derivatives contain `NaN` and the step size returned by `newStepSizeFunction_` is `NaN` as a result of that, the step size should be rejected. This is not happening, as `NaN` is not accounted for, and any comparison with `NaN` just returns false. The resulting `NaN` step size is instead used, invalidating the entire remainder of that trajectory.

https://github.com/tudat-team/tudat/blob/234ec857a3c7c8649dbd9fe1f7b461d4283ae338/include/tudat/math/integrators/rungeKuttaVariableStepSizeIntegrator.h#L632-L645

One example of where this can happen, is when propagating dynamics in MEE elements. The `p` element may be decreasing (i.e., have a negative derivative) yet it cannot, by definition, be smaller than zero. When taking too great of a step, `p` can turn negative in one of the integration stages and, as a result of that, return `NaN` derivatives. This can, of course, be prevented by limiting the maximum allowable step size, yet that just adds more steps than would be necessary if the step size control was working.

**Comment by briha** [comment]
Here's a wrapper for `RungeKuttaVariableStepSizeIntegrator` that deals with this, by just attempting a smaller step size if the current attempted one results in `NaN`.

```cpp
namespace tudat {
namespace numerical_integrators {
    
template<typename TimeType = double, typename StateType = Eigen::VectorXd, typename dStateType = StateType, typename dTimeType = TimeType>
class NaNProofRungeKuttaVariableStepSizeIntegrator
        : public RungeKuttaVariableStepSizeIntegrator<TimeType, StateType, dStateType, dTimeType> {
public:

    typedef RungeKuttaVariableStepSizeIntegrator<TimeType, StateType, dStateType, dTimeType> WrappedType;

    NaNProofRungeKuttaVariableStepSizeIntegrator(const std::shared_ptr<WrappedType> &toWrap, const TimeType nextIterationTimeFactorUponNaN)
            : WrappedType(*toWrap), nextIterationTimeFactorUponNaN(nextIterationTimeFactorUponNaN) {


        this->newStepSizeFunction_ = [this](const dTimeType stepSize, const std::pair<dTimeType, dTimeType> &orders,
                                            const dTimeType safetyFactorForNextStepSize,
                                            const std::pair<dTimeType, dTimeType> &minimumAndMaximumFactorsForNextStepSize,
                                            const StateType &relativeErrorTolerance,
                                            const StateType &absoluteErrorTolerance,
                                            const StateType &lowerOrderEstimate,
                                            const StateType &higherOrderEstimate) {
            std::pair<dTimeType, bool> originalResult = WrappedType::computeNewStepSize(stepSize, orders, safetyFactorForNextStepSize,
                                                                                        minimumAndMaximumFactorsForNextStepSize,
                                                                                        relativeErrorTolerance,
                                                                                        absoluteErrorTolerance,
                                                                                        lowerOrderEstimate,
                                                                                        higherOrderEstimate);

            if (lowerOrderEstimate.array().isNaN().any()) {
                originalResult.first = stepSize * this->nextIterationTimeFactorUponNaN;
                originalResult.second = false;
            }

            return originalResult;
        };

    }

protected:
    TimeType nextIterationTimeFactorUponNaN;
};

}  // numerical_integrators
}  // tudat
```

One way it could be accelerated, is if the new state function used the [`.template maxCoeff<Eigen::PropagateNaN>();`](https://eigen.tuxfamily.org/index.php?title=3.4#Improvement_to_NaN_propagation) instead of the default (undefined) `NaN` propagation behaviour. If that happened, the check to invalidate would not need to go through the entire state vector again, and could just do a NaN-check on the suggested `stepSize`. This may or may not have an impact on normal propagation, where no NaN is to be expected, however, as [`PropagateFast`](https://eigen.tuxfamily.org/dox/group__enums.html#gga7f4e3f96895bdb325eab1a0b651e211fa917fa8982b7eb0cbb440d38ee50e0b9c) is the default behaviour. Potentially making this a template option to take that into account might be an idea.

https://github.com/tudat-team/tudat/blob/234ec857a3c7c8649dbd9fe1f7b461d4283ae338/include/tudat/math/integrators/rungeKuttaVariableStepSizeIntegrator.h#L717-L718

**Comment by DominicDirkx** [comment]
Hi @briha, apologies for the late reply, and thanks for posting a preliminary solution! As a little background on this, it is true that the current behaviour is not optimal, it leads to issues in the evaluation of the state derivative (with t=NaN). In a Tudat propagation, this raises an exception that is handled properly, but it does limit the stand-alone applicability of the integrator. One of this things on our todo-list is to make a more general time-step control scheme, where a user can provide specific settings to the time-step control (and even a fully customized time-step control algorithm). I think this issue is best resolved in the context of that, but for now what you have implemented looks like a good alternative, which does not impact any existing functionality.

**Comment by briha** [comment]
One note here: The behaviour of how NaNs are dealt with in `maxCoeff` is actually really undefined. The derivative containing NaNs does not necessarily mean that the time step will be NaN too. So for a trajectory that does fail, it can fail in two ways:

- An exception (t=NaN) is actually thrown. This happens when the time turns NaN too.
- It fails silently: The integration just continues until it reaches the step limit I set. From the point on, where NaN is encountered, the full state vector is NaN. The time continues to be a real value. This was actually way more common than the first case, interestingly.

I think, at the very least, consistent behaviour here would be nice. But, of course, a more clear framework for dealing with custom step size control would be nice, so I am glad to hear it is coming!

**Comment by DominicDirkx** [comment]
Resolution of issue will be tracked here: https://github.com/tudat-team/tudat/issues/166
