### ISSUE TITLE
Misspelling, unknown ramifications: semiPerimeter > semiParameter

### ISSUE THREAD

**Issue by transferorbit** [tudat-team/tudat#156]
In `lambertRoutines.h`, in the function `computeTimeOfFlightIzzo`, the argument `semiPerimeter` should be `semiParameter`.

[code link](https://github.com/tudat-team/tudat/blob/d22ae013e8f212cbbc4e313f83e3d2cb1092c4fb/include/tudat/astro/mission_segments/lambertRoutines.h#L82)

**Comment by DominicDirkx** [comment]
In principle, this doesn't matter (in the .h file you can even omit the variable names altogether, so long as the types are correctly listed). But, this is definitely misspelled, so please do feel free to open a pull request to fix this (and any other spelling errors you may find!)
