### ISSUE TITLE
Change of simulated observations depending on origin

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#160]
When simulating DSN Doppler observations, the behavior of the residuals changes depending on the origin used for the ephemerides origin. Tested for MGS, when in orbit around Mars, considering the origin of the ephemerides to be SSB, Mars or Earth:
- If (1) SSB as origin for planets, (2) planet or SSB as origin for spacecraft: "normal" residuals
- If (1) planet as origin for planets,  (2) planet or SSB as origin for spacecraft: noticeably larger residuals

EDIT: The global origin is set to coincide with the ephemerides origin of the planets (via getDefaultBodySettings). 

Plots for the 4 cases, when considering Mars to be the origin planet: [plots.zip](https://github.com/tudat-team/tudat/files/11667283/plots.zip)
In the case of Earth as origin planet, the same results are obtained (just small differences that appear to be a result of numerical errors).
This data was generated via: https://github.com/MiguelAvillez/tudat/blob/cc788aa90d4972bce45e465f1ca76f784ef14955/tests/src/astro/observation_models/unitTestDsnOdfObservationModels.cpp

While looking for a source of this difference, I believe I found a bug in the templates when creating the system of bodies. Following the order of the function calls: 
1) createSystemOfBodies( )
2) processBodyFrameDefinitions( )
3) setGlobalFrameBodyEphemerides( ): called without specifying the templates, hence having StateScalarType = double, TimeType = double. Thus when calling setEphemerisFrameToBaseFrame( ), the function to convert between the two frames is always set to double (double). 

However, this bug doesn't explain the different behaviors of the residuals: it shouldn't cause any difference for the situations where the global and ephemerides origins coincide, i.e. where they're either both the SSB or both one of the planets, but as mentioned above the error in the residuals does occur when both origins are set to a planet.

**Comment by DominicDirkx** [comment]
This issue is based in a misunderstanding. The observable _should_ be different for different frame origins. If the Earth is the origin, the frame origin will be accelerating, which will induce a modification of the observable, due to relativistic effects (e.g. change of relativistic reference frame and length/time scale)
