### ISSUE TITLE
Handling of condition number in least squares

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#164]
Currently a warning is thrown if the condition number is above a certain value ([warning](https://github.com/tudat-team/tudat/blob/a35812a3353314d35793c2ce45311934577adae4/src/math/basic/leastSquaresEstimation.cpp#L54)), which is currently hard coded to 10e8 ([here](https://github.com/tudat-team/tudat/blob/a35812a3353314d35793c2ce45311934577adae4/include/tudat/simulation/estimation_setup/orbitDeterminationManager.h#L738)). 

The user should be given more flexibility to choose how to deal with these warnings, e.g. choosing the condition number above which a warning is thrown, choosing whether or not the warning is thrown, choosing when the warning is thrown (just on first iteration, on all iterations), ...

**Comment by DominicDirkx** [comment]
Required modifications have been made here: https://github.com/tudat-team/tudat/pull/183

A new option is added to the CovarianceAnalysisInput class, which represents the limit value for a condition number warning. The EstimationInput has a boolean option to only print the warning on the 1st iteration. Documentation will follow with associated tudatpy pull request.
