### ISSUE TITLE
Final iteration residuals in estimateParameters

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#176]
For the final iteration of [estimateParameters()](https://github.com/tudat-team/tudat/blob/4f7c86e647d6b1ab2140a5348e4a044539fdea5a/include/tudat/simulation/estimation_setup/orbitDeterminationManager.h#L685-L686), the parameters are updated but the residuals resulting from that update are never computed. This also leads to an inconsistent number of values in the parameter history and the residual history (the former has one extra element). Correct this :)

**Comment by DominicDirkx** [comment]
Required modifications have been made here: https://github.com/tudat-team/tudat/pull/183

The 'parameter estimate' that is provided as output is not always one for which the residuals have been calculated, and not one that is computed with the correction based on the last residuals. There is an option (default true) to add this final correction (for which the quality is not directly evaluated) to the EstimationOutput. Documentation will follow with associated tudatpy pull request.
