### ISSUE TITLE
Dependent variable shape access from within SingleArcPropagator

### ISSUE THREAD

**Issue by alopezrivera** [tudat-team/tudat#179]
# Context

Hi! First of all, thank you for your work! For context, I use tudat through the Python tudatpy interface. If any reference to an object or function I make is not clear it may be due to this, please let me know and I'll clarify as needed.

Tudat allows to store a breadth of dependent variables in simulations. Currently, it is possible to access the string ID of each of these dependent variables directly from within the *SingleArcPropagator* object obtained from the propagation (in tudatpy, returned by `tudatpy.kernel.numerical_simulation.create_dynamics_simulator`).

# Need

It would be very useful to have access to the shape of the dependent variables that are being saved (scalar, vector, matrix), besides their ID.
This information is contained inside the *SingleDependentVariableSaveSettings* objects given in tudatpy to the `tudatpy.kernel.propagation_setup.propagator.translational` function, and is accessible as an attribute of those objects at least in C++.

# Request
It would be very appreciated to

- In Python, expose/make it possible to access the shape of the saved dependent variables from their respective *SingleDependentVariableSaveSettings* object
- In C++ and Python, make the *SingleDependentVariableSaveSettings* object of each saved dependent variable accessible from the *SingleArcPropagator* object resulting from the propagation

**Comment by DominicDirkx** [comment]
Required functionality should now be available through the following updates:

https://github.com/tudat-team/tudat/pull/181
https://github.com/tudat-team/tudatpy/pull/111

A few additional tests need to be run, but you can use it for development purposes for now.

**Comment by DominicDirkx** [comment]
Functionality is now merged, and a new issue with a loose end is opened here:

https://github.com/tudat-team/tudat/issues/182

the remaining open issue already existed before the modifications in the above pull request, so there's no reason not to merge these ones already
