### ISSUE TITLE
Request: Dedicated, early Error Message for missing bias settings

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat#18]
When adding acceleration model parameters to the parameter set, there is a nice mechanism that checks for the required acceleration model information to be present during the creation of the parameter set.
A similar feature does not seem to exist for observation model parameters (at least not range biases).

As of now it seems as if there is no mechanism to warn the user about missing observation model information when adding observation model parameters to the parameter set. 
Instead, the user is confronted with a 

RuntimeError: std::exception 

during the tss::OrbitDeterminationManager< >::estimateParameters function.

A feature similar to that checking for consistency between acceleration model and acceleration model parameters would be appreciated for observation model and observation model parameters.

**Comment by DominicDirkx** [comment]
A quick browse through the code indicates that there is a check to do this, but apparently it is no robust. Do you have a script in which this error manifests itself?

**Comment by DominicDirkx** [comment]
Improved error output has been pushed here:

https://github.com/tudat-team/tudat/tree/feature/bias_estimation_robustness

Could you try this out, and see if it indeed addresses the issue you raised?

**Comment by DominicDirkx** [comment]
I've checked this locally, and have merged this into a larger branch with improved error output

https://github.com/tudat-team/tudat/tree/feature/improved_error_output

**Comment by DominicDirkx** [comment]
Code merged
