### ISSUE TITLE
Request: Phase out special functions for setup of aerodynamic and radiation pressure interfaces

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat#19]
Consider phasing out `addAerodynamicCoefficientInterface` function to force consistent environment_setup via assignment of settings object to settings attribute of BodySettings object. 
Analogously for `addRadiationPressureInterface`.

**Comment by jo11he** [comment]
@DominicDirkx feel free to invite other members to this thread if you want to get a discussion going.

**Comment by DominicDirkx** [comment]
Tagging @FilippoOggionni, @ggarrett13. The reason these functions are in here is to save users a single step. It may indeed be better to have them do this step, would also make it more clear what the underlying code does.

**Comment by jo11he** [comment]
I am in favour of this, which is why I am raising the issue.

**Comment by FilippoOggionni** [comment]
I am also in favor of @jo11he's proposal, as I think it would provide more consistency. If there is no specific reason other than the one mentioned by @DominicDirkx , then I would remove the two functions to be aligned with the workflow of all other settings (i.e., through attributes of `BodySettings`).

**Comment by DominicDirkx** [comment]
One important thing to realize, in this case there would not be (or need not be) any BodySettings.

**Comment by FilippoOggionni** [comment]
> One important thing to realize, in this case there would not be (or need not be) any BodySettings.

What do you mean?

**Comment by DominicDirkx** [comment]
When going through the add_... workflow as now available, the Body object for a vehicle is created 'manually' (no BodySettings object), and the only settings class object that is used relates to a single environment modle

**Comment by DominicDirkx** [comment]
After some more refactoring/extension, we've decided to keep the add_... interfaces, in particular to be able to modify the environment after its initial creation. It will not be the 'default' way of setting anything up
