### ISSUE TITLE
final_residuals returning best residuals, not final

### ISSUE THREAD

**Issue by FDahmani** [tudat-team/tudat#198]
I have noticed that when using the following function https://py.api.tudat.space/en/latest/estimation.html#tudatpy.numerical_simulation.estimation.EstimationOutput.final_residuals ,the values you get are from the 'best', i.e. lowest printed 'Current residual' in the estimation process, not of the actual final residual. In the added output in the txt file, you can also see that the claimed final residual is in fact the first one, that just happens to be the best one, which is likely a coupled problem. In the images you can see the residuals in the first and fith iteration. The final image demonstrates the residuals from the function mentioned earlier, which is the same as the first, not the last iteration, as it is supposed to be.
[residuals.txt](https://github.com/tudat-team/tudat/files/14112060/residuals.txt)
![0_720](https://github.com/tudat-team/tudat/assets/64595872/e21b2ff8-80be-4737-aafa-1ea9609a4874)
![4_720](https://github.com/tudat-team/tudat/assets/64595872/78996812-5ab6-4555-b587-b438eb5c1dfe)
![residuals_720](https://github.com/tudat-team/tudat/assets/64595872/5fe43aec-6d6c-4e2e-b79d-09571bd72678)

**Comment by FDahmani** [comment]
To provide some more context, and perhaps a more clear case to reproduce: 

1. Residuals from final_residuals
2. Residuals at iteration 1 from residual_history
3. Residuals at iteration 5 from residual_history
4. The difference in position between estimated orbit and SPICE benchmark, very bad fit

Thus note that the final_residuals in fact are the same as the ones from the first iteration. Both input files and the file to run can be found in the zip. Make sure to change line 83 to the correct directory and to have the correct Spice kernel available(jup344.bsp)  

![Residuals](https://github.com/tudat-team/tudat/assets/64595872/1c7fec11-e16a-4621-bd9a-c944004f1f8c)
![0](https://github.com/tudat-team/tudat/assets/64595872/fb3757fe-7e70-4933-ba16-e1d60c96737e)
![4](https://github.com/tudat-team/tudat/assets/64595872/97a7e51b-47e4-471b-b2d2-269d39237297)
![PosDifference](https://github.com/tudat-team/tudat/assets/64595872/cc053da8-7727-4d5d-b444-fcb8422db7db)
[Inputfiles.zip](https://github.com/tudat-team/tudat/files/14137626/Inputfiles.zip)

**Comment by DominicDirkx** [comment]
Issue corrected in documentation (to be built)
