### ISSUE TITLE
Automatically add empty tabulated ephemeris when needed

### ISSUE THREAD

**Issue by DominicDirkx** [tudat-team/tudat#20]
When setting the results of a numerical propagation using the Simulator (https://tudatpy.readthedocs.io/en/latest/numerical_simulation.html#tudatpy.numerical_simulation.SingleArcSimulator, set_integrated_result = true), the propagated body needs to have a compatible ephemeris. If it does not, it crashes at present (with an error?), This can be made more robust by adding an ephemeris 'on the fly'

**Comment by DominicDirkx** [comment]
Some progress has been made:

https://github.com/tudat-team/tudat/tree/feature/automatic_tabulated_ephemeris

The modifications have been checked with selected unit tests. Modification will not work (yet) for multi- and hybrid-arc

**Comment by DominicDirkx** [comment]
All unit tests are now passing, but the automatic creation of a tabulated ephemeris (either translational or rotational) is only working for single arc. When using a multi-arc propagation, and wanting to reset the ephemeris, a user still needs to manually define a multi-arc ephemeris in the body that is to be propagated.

**Comment by MarieFayolle** [comment]
Hi Dominic, I gave it a look and I completely agree with you that it is better to push the single arc code now and wait for the coming modifications of the multi arc propagation. Especially, one think on my todo list for next week is to modify how to reset ephemerides in the multi-arc case, so I guess it makes perfect sense to wait for those changes.

**Comment by DominicDirkx** [comment]
Code has been merged :)
