### ISSUE TITLE
Insufficient ephemeris data has been loaded

### ISSUE THREAD

**Issue by csb2024** [tudat-team/tudat#200]
I am using version 2.11 of Tudat. When we were debugging and running, we encountered the error "Independent ephemeris data has been loaded". Prior to this, I found that some ephemeris files required for the Tudat 2.11 runtime were not included in the Tudat resources-2.2 directory. Can you provide the complete data files and corresponding cspice project build files and source code?
![bug](https://github.com/tudat-team/tudat/assets/162396831/0eeb504d-1d22-4e63-926e-762f486aba4b)

**Comment by DominicDirkx** [comment]
Hello, from the looks of this error you are not loading any spice kernels (or, not the default ones). Manually downloading the data files in tudat-resources can be done according to the steps described here:

https://docs.tudat.space/en/latest/_src_getting_started/faq.html#tudat-cannot-find-data-files-that-it-needs

If this doesn't resolve your issue, please let me know, and add a link to the file you're running. That way, we can try to help you out in more detail

**Comment by csb2024** [comment]
Thank you for your reply. The issue has not been resolved.

I am using the Windows 10 operating system and compiled using VS2019 as a static library. I have modified the path related functions:

Static inline std:: string get_hiddenpath(){

//Return std:: string (std:: string (get_homedir())+"/. tudat"). csstr();

Return std:: string (std:: string (get_homedir())+"/tudat"). csstr();

}


Static inline char * get_homedir (void){

Char home [MAX-PATH];

#Ifdef_WIN32

//Snprintf (homedir, MAX-PATH, "% s% s", getenv ("HOMEDRIVE"), getenv ("HOMEPATH"));

Snprintf (home, MAX-PATH, "% s", getenv ("TUDAT-DATA-PATH"));

#Else

Snprintf (homedir, MAX-PATH, "% s", getenv ("HOME"));

#Endif

Return strdup (homedir);

}
All files in spice_kernels path(Copy from tudat-resources-2.2) are:
![图片](https://github.com/tudat-team/tudat/assets/162396831/e169a9dc-aa3d-42d5-b32d-2335f1a1a1a2)
my test project is singlePerturbedSatellitePropagator in satellite_propagation example folder

**Comment by DominicDirkx** [comment]
The C++ examples on our repository are, at the moment, not up-to-date with the latest version of the code. I would recommend you use our Python interface (https://docs.tudat.space/en/latest/), or to take the code of the example application in the latest version and update it to run properly.

If you can give some background on your use of Tudat, we can support you in this process.

**Comment by csb2024** [comment]
Thank you for your reply! I want to use Tudat for simulation applications, so there are certain performance requirements. Therefore, I will test the C++example first. Can you suggest a stable version of C++and a corresponding data version?

**Comment by DominicDirkx** [comment]
The performance difference between the Python and C++ interface is very limited, since in both cases the simulations are done using the same compiled C++ code. In the Python interface case, this is achieved using the pybind11 package.

At the moment, we do not have any C++ examples up and running, but this is on our todo list. However, we have many (>250) unit tests, many of which can serve as an example application. If you're really set on using the C++ interface, and you can explain your specific use case a little more, I can point you in the direction of a suitable unit test that can serve as an example.
