### ISSUE TITLE
Documentation of angular_position() and relative_angular_position()

### ISSUE THREAD

**Issue by lrbusquets** [tudat-team/tudat#210]
The equations [(https://py.api.tudat.space/en/latest/observation.html#tudatpy.numerical_simulation.estimation_setup.observation.angular_position](displayed) in the API documentation for both methods of the observation module are apparently the same when they should not. Following @DominicDirkx 's indications, I open this issue here.

**Comment by DominicDirkx** [comment]
Corrected in the multidoc repo; the docs will be updated after the next succesful tudatpy conda package build
