### ISSUE TITLE
[Bug] Build fails for MacOS in CI pipeline

### ISSUE THREAD

**Issue by niketagrawal** [tudat-team/tudat#212]
Build fails on MacOS in the CI pipeline from the commit [1a9aa2e](https://github.com/tudat-team/tudat/commit/1a9aa2e01557b527a4fef48ab0eac259deb161d6) onwards. The failure is not related to the code changes in the commit. 

This failure seems to be due to a dependency incompatibility, for example, a potential upgrade in the version of the `boost-cpp` conda package that is downloaded and installed as part of the CI workflow. 

Error text in [CI log](https://github.com/tudat-team/tudat/actions/runs/8986008928/job/24681147364) points to missing osx compatible boost libraries.

```
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_filesystem.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_system.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_regex.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_date_time.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_thread.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_chrono.dylib': found architecture 'x86_64', required architecture 'arm64'
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_atomic.dylib': found architecture 'x86_64', required architecture 'arm64'
[ 41%] Building CXX object src/simulation/estimation_setup/CMakeFiles/tudat_estimation_setup.dir/createAtmosphericLightTimeCorrection.cpp.o
ld: warning: ignoring file '/Users/runner/miniconda3/envs/tudat/lib/libboost_unit_test_framework.dylib': found architecture 'x86_64', required architecture 'arm64'
```

**Comment by niketagrawal** [comment]
The CI workflow for MacOS starts with the `macos-latest` runner image and then installs `boost-cpp` via conda, so I would assume that the boost libraries that are installed are compatible for MacOS. Since the conda environment cache is cleared daily, the case of old x86 boost libraries lingering around in the runner environment is also ruled out. 

The version of the conda package `boost-cpp` hasn't changed between the last successful CI run and the first failure.

**Comment by yiquintero** [comment]
Two important system differences are observed between the [last successful](https://github.com/tudat-team/tudat/actions/runs/8673544936) workflow execution and the [first failing one](https://github.com/tudat-team/tudat/actions/runs/8986008928):
- The macOS-latest runner was updated from v. 2.315.0 (macOS v.12.7.4) to v. 2.316.1 (macOS v. 14.4.1)
See lines 1-5 of the "Set up Job" section of the log file
- The C++ compiler was updated from v.14.0.0.14000029 to v.15.0.0.15000040
See line 51 of the "Configure CMake " section of the log file

**Comment by yiquintero** [comment]
https://github.com/conda-incubator/setup-miniconda/issues/312
