### ISSUE TITLE
Request: easier access to covariance history in TNW 

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat#22]
(sorry for python syntax)

Enable easier access to TNW covariance history by implementing two features:

- [x] transform_covariance_history_to_frame( inertial_covariance_history, state_history, target_frame_id ) function
- [x] enable retrieval of state_history from Estimator object

such that user can do the following to obtain TNW (post-fit) covariances along an given tracking arc:

`// exists
Estimator = numerical_simulation.Estimator()
pod_output = Estimator.perform_estimation()
initial_covariance = pod_output.covariance

// new
propagation_timeline = list(Estimator.state_history)
states = np.vstack(Estimator.state_history.values())

// exists
covariance_history = estimation.propagate_covariance(
                initial_covariance,
                Estimator.state_transition_interface,
                propagation_timeline)          <-- use timeline from Estimator object here for same resolution

// new 
covariance_history_in_tnw = transform_covariance_history_to_frame( 
                covariance_history,            <-- automatically have covariance_history and 
                states,                        <-- state_history at same timeline here
                target_frame_id )`

**Comment by DominicDirkx** [comment]
I've made some progress, and pushed it here:

https://github.com/tudat-team/tudat/tree/feature/covariance_transformation

code is untested

**Comment by DominicDirkx** [comment]
I've made the necessary modifications to the code, but have not yet created test cases. I'm having some trouble coming up with a robust test case for the covariance transformation. What I would think of:
* Check if a manual calls to the new convertCovarianceToFrame function does the same as automatic (per-epoch) calls via the convertCovarianceHistoryToFrame function. This is perfectly doable
* Check if the transformation of the full covariance happens correctly. Here, it's quite straightforward to check if automatic transformation of the covariance works correctly if compared against a 'manual'  transformation. This is plan B. Plan A is defining a case where we can deduce the correct transformed result based on physical consideration. @jo11he , @MarieFayolle: if you have any ideas for this, I'm all ears!
