### ISSUE TITLE
Add custom dependent variable

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat#34]
- [x] Add to the list of available dependent variable a "custom" variable. The user can provide a function to compute the dependent variable.
- [x] Expose it in tudatpy
- [ ] Document it in API reference and user guide

**Comment by DominicDirkx** [comment]
Custom dependent variable has been added here:
https://github.com/tudat-team/tudat/tree/feature/new_dependent_variables
But no unit test has been written yet

**Comment by DominicDirkx** [comment]
I've merged the code in tudat, and the exposure in tudatpy, into their develop branches (now including a unit test).

I have made a draft version of the docstrings:

https://github.com/tudat-team/tudat-multidoc/tree/feature/custom_dependent_variable

But, I am not very happy with it.... @FilippoOggionni or @gaffarelj, could you take a look and update it? I think it could also do with an example (in the unit test, I used the ratio of two bodies' states)

**Comment by gaffarelj** [comment]
I can take care of improving the docstrings and adding an example.

For the example, I was thinking of a basic computation of air mass flow for a space-plane-like vehicle. I can then take values from the flight conditions such as the airspeed, density, and angle of attack, and compute it with <img src="https://latex.codecogs.com/png.latex?\bg_white%20\dot{m}%20=%20\rho%20\cdot%20A%20\cdot%20V%20\cdot\cos%20\alpha"/>. But I'm of course open to any other suggestions.

**Comment by FilippoOggionni** [comment]
I like the idea @gaffarelj. It is simple enough but at the same time it involves variables from the environment (density) and the vehicle (velocity), so I would go for it!

**Comment by DominicDirkx** [comment]
Sounds good, I like the idea of showcasing the extraction of variables from the flight conditions. The value A here would then be the reference area of the aerodynamic coefficients, right?

**Comment by gaffarelj** [comment]
Yes, `A` will be a fixed area.
I will then get on it later today or tomorrow :)

**Comment by gaffarelj** [comment]
I've created the example. I must say, I am a fan of this functionality already 🙂

My example computes the mass flow getting through a 35cm$^2$ inlet of a rocket on Mars.

This results in the following dependent variable values over time (second plot is altitude [km] on y-axis):
![image](https://user-images.githubusercontent.com/50528981/151018585-a2950d04-042f-428e-a393-9bdd464df770.png)

I have slightly updated the docstrings, and included the code snippet in it. This is pushed with [c2891c7](https://github.com/tudat-team/tudat-multidoc/commit/c2891c7380ca5fbd61ecbd1f2913fe066cfc7251).

**Comment by DominicDirkx** [comment]
Nice! Would the code you used for this be suitable for an example application? It looks like it could fill a good niche there as well

**Comment by gaffarelj** [comment]
I think it could, yes.
I am currently developing this ascent code as part of my MSc thesis. I will then convert the core of it to an example when this code has matured a little bit.

**Comment by DominicDirkx** [comment]
Great! I suggest we make a separate issue out of that. As far as I'm concerned, this issue can be closed

**Comment by gaffarelj** [comment]
Yes, I opened [this issue](https://github.com/tudat-team/tudatpy-examples/issues/6) accordingly.

If this is closed, should I merge the [feature/custom_dependent_variable](https://github.com/tudat-team/tudat-multidoc/tree/feature/custom_dependent_variable) branch in `tudat-multidoc` with `main`?
