### ISSUE TITLE
Feature request: dep. vars. based on multiple bodies

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#36]
A set of new dependent variables could be added that are based on multiple simulation bodies.

This allows for instance to save over time:

- Amongst a constellation of satellites, what is the closest to a given sat, and what is the distance between them.
- From a satellite constellation, what is the closest to a given coordinate on Earth (a ground station for instance), and what is the distance between them.

This dependent variable would then save two elements:

- What is the name of the body the closest to a specified one.
- What is the distance between the two bodies.

**Comment by DominicDirkx** [comment]
The developer guide for this can now be found here:
https://cpp.api.tudat.space/developerGuide/addingFeatures/addingDependentVariablesToSave.html
which is still to be added to the new documentation

**Comment by DominicDirkx** [comment]
Below is a branch with (untested!) the first proposed dependent variable implemented:
https://github.com/tudat-team/tudat/tree/feature/constellation_dependent_variables
One important note: the calculations ignore light time

**Comment by DominicDirkx** [comment]
I've also added a (preliminary, untested) implementation of the 2nd idea. I want to think about this part a little more, as it requires interaction with a ground station, which thus far never happens during the propagation. It should be able to, but there may be a better way to do it than implemented now

**Comment by DominicDirkx** [comment]
Unit tests now added. To be done:

- [ ] Expose to Python

- [ ] Write docstrings

What is not done, is a check for the mininum intersatellite distance whether the satellites are visible to one another (e.g. not obscured by a central body). I'll leave it like this for now, and add this to the docstrings.
