### ISSUE TITLE
Add interface to change density model inputs

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat#40]
Currently, the density values are retrieved from NRLMSISE-00 based on the date of the simulation. It would be nice to be able to play around with the inputs of the density model itself, without being tied to the date.

**Comment by DominicDirkx** [comment]
Good point, there is also a relation with issue #38, as both relate to the reading and handling of the data file(s) from which NRLMSISE-00 does is computation

**Comment by DominicDirkx** [comment]
@FilippoOggionni, as a resolution of this issue, would the ability to input a user-defined file for solar activity, etc. be sufficient, or did you have something else in mind?

**Comment by FilippoOggionni** [comment]
I think so, yes. I did not have anything specific in mind, but as long as we can uncouple the simulation date from the density it will be good. 

From the top of my head, I can't tell exactly the inputs necessary for the density model, but providing all the required ones (solar flux F10.7 and magnetic indices like Ap and Kp) is already a great start.

Was there a specific reason why you were thinking about a file and not interface functions?

**Comment by DominicDirkx** [comment]
> Was there a specific reason why you were thinking about a file and not interface functions?

Only that using a file is how this is done now, and tackling the problem at this level is easiest

**Comment by DominicDirkx** [comment]
> I think so, yes. I did not have anything specific in mind, but as long as we can uncouple the simulation date from the density it will be good.

What did you mean with this exactly? You want the density profile to be independent of time?

**Comment by FilippoOggionni** [comment]
> What did you mean with this exactly? You want the density profile to be independent of time?

So, at the moment the density is obtained as follows (please correct me if I am wrong): epoch -> solar activity indices at given epoch -> density based on those solar indices. What I would like to have is to simulate certain conditions (e.g., giving solar activity as input) at an arbitrary time. Again, correct me if I am wrong, but from my understanding the dependency of density on time is only caused by solar activity indices at given epochs, right?

**Comment by DominicDirkx** [comment]
Right, got it. I propose we split this activity in two, one allowing to provide a new input file (easy), the other allowing to provide vustom values for NRLMSISE input

**Comment by DominicDirkx** [comment]
Just checked, the required input to NRLMSISE is:

```
/* Array containing the following magnetic values:
 *   0 : daily AP
 *   1 : 3 hr AP index for current time
 *   2 : 3 hr AP index for 3 hrs before current time
 *   3 : 3 hr AP index for 6 hrs before current time
 *   4 : 3 hr AP index for 9 hrs before current time
 *   5 : Average of eight 3 hr AP indicies from 12 to 33 hrs 
 *           prior to current time
 *   6 : Average of eight 3 hr AP indicies from 36 to 57 hrs 
 *           prior to current time 
 */


struct nrlmsise_input {
	int year;      /* year, currently ignored */
	int doy;       /* day of year */
	double sec;    /* seconds in day (UT) */
	double alt;    /* altitude in kilometers */
	double g_lat;  /* geodetic latitude */
	double g_long; /* geodetic longitude */
	double lst;    /* local apparent solar time (hours), see note below */
	double f107A;  /* 81 day average of F10.7 flux (centered on doy) */
	double f107;   /* daily F10.7 flux for previous day */
	double ap;     /* magnetic index(daily) */
	struct ap_array *ap_a; /* see above */
};
```

**Comment by FilippoOggionni** [comment]
> I propose we split this activity in two, one allowing to provide a new input file (easy), the other allowing to provide vustom values for NRLMSISE input

What would be the difference between the two solutions? Would the inputs be the same but provided through different means?

> Just checked, the required input to NRLMSISE is:

Thanks for posting this, it is really useful. Giving the possibility to users to manually modify all those inputs would be great (although not high priority). 

In addition, I have a question: what happens when you simulate drag in the future? I guess the NRLMSISE-00 model does not have access to solar activity data anymore, right? So how does it work? (This issue is also related, but not limited, to #38)

**Comment by DominicDirkx** [comment]
The input file is specifically of this format:

https://raw.githubusercontent.com/tudat-team/tudat-resources/master/resource/space_weather/sw19571001.txt

This file gets read, and parsed into a function of type:

typedef std::function< NRLMSISE00Input( double, double, double, double ) >

where inputs are altitude, latitude, longitude, time (see nrlmsise00Atmosphere.h/.cpp). The NRLMSISE00Input struct corresponds mostly to what I showed above. The creation of this function from the data file happens in nrlmsise00InputFunctions.h/.cpp.

To create a setup whereby a user can provide a custom input to the atmosphere model, we would have to think at which level we would want to do this, for which there are a number of options. I suggest that we tackle this at an upcoming developer meeting. It also relates to the broader picture of how we deal with Space Weather data.

**Comment by DominicDirkx** [comment]
> In addition, I have a question: what happens when you simulate drag in the future? I guess the NRLMSISE-00 model does not have access to solar activity data anymore, right? So how does it work? (This issue is also related, but not limited, to #38)

The space weather input file has predictions of solar activity several years into the future. I do see in the file that the prediction of geomagnetic activity is largely absent, so I assume this gets set to zero (or some default?)

**Comment by DominicDirkx** [comment]
I've made a few modifications to the NRLMSISE functions:

https://github.com/tudat-team/tudat/tree/feature/nrlmsise_update
https://github.com/tudat-team/tudatpy/tree/feature/nrlmsise_update

As it turns out, it was already very easily possible to load a different space weather file. This was just not exposed to Python :) The problem has been corrected. Before merging, this may need an improved unit test for related functionality (see #38)

**Comment by DominicDirkx** [comment]
Closing issues; remaining issue(s) being tracked through #38

**Comment by DominicDirkx** [comment]
I have made a few small modifications to facilitate this. From the NRLMSISE atmosphere model, you can now retrieve the solar activity object that will be used for a given epoch:
https://github.com/tudat-team/tudat/blob/feature/nrlmsise_update/include/tudat/astro/aerodynamics/nrlmsise00Atmosphere.h#L381-L384
https://github.com/tudat-team/tudat/blob/feature/nrlmsise_update/include/tudat/io/solarActivityData.h#L184-L188
This solar activity container contains the following (custom-made for NRLMSISE):
https://github.com/tudat-team/tudat/blob/feature/nrlmsise_update/include/tudat/io/solarActivityData.h#L47-L165

I'm a bit hesitant to completely refactor this to allow the density calculation to be decoupled from the data. What this interface does allow you is, for a given date (or given time interval) modify any of the NRLMSISE inputs to a value of your choosing. For which quantities do you think this would be useful (I guess F10.7; Ap?)

**Comment by FilippoOggionni** [comment]
> I'm a bit hesitant to completely refactor this to allow the density calculation to be decoupled from the data.

What are the reasons? Just curious 😄 

> For which quantities do you think this would be useful (I guess F10.7; Ap?)

To answer this, I'd need to check exactly which inputs are needed by NRLMSISE model (e.g., I remember it uses the daily flux but also the 81-day average, but also adjusted vs. observed, etc...). In general, I would say those two (F10.7, Ap) are the ones that people would be interested in, but I cannot tell you which "variants". However, if you search by time, I guess all values can be looked up for that specific epoch and fed to the model, right?

**Comment by DominicDirkx** [comment]
> What are the reasons? Just curious
Purely the trade-off of time required vs. improvement in functionality

Looking at the code here:
https://github.com/tudat-team/tudat/blob/feature/nrlmsise_update/src/astro/aerodynamics/nrlmsise00InputFunctions.cpp
It takes:

 

>    if( solarActivity->fluxQualifier == 1 )
>     { // requires adjustment
>         nrlmsiseInputData.f107 = solarActivity->solarRadioFlux107Adjusted;
>         nrlmsiseInputData.f107a = solarActivity->centered81DaySolarRadioFlux107Adjusted;
>     }
>     else
>     { // no adjustment required
>         nrlmsiseInputData.f107 = solarActivity->solarRadioFlux107Observed;
>         nrlmsiseInputData.f107a = solarActivity->centered81DaySolarRadioFlux107Observed;
>     }
>     nrlmsiseInputData.apDaily = solarActivity->planetaryEquivalentAmplitudeAverage;
>     nrlmsiseInputData.apVector = eigenToStlVector( solarActivity->planetaryEquivalentAmplitudeVector );

**Comment by FilippoOggionni** [comment]
> planetaryEquivalentAmplitudeVector (not sure what it is)

I think the daily Ap (scalar) is the average of 8 measurements per day (one every 3 hours), so the `planetaryEquivalentAmplitudeVector` might simply be a vector containing 8 values? Just guessing here 🙂

**Comment by DominicDirkx** [comment]
The following tasks should cover the missing functionality:

- [ ] Expose the SolarActivityContainer and SolarActivityData classes, and allow these to be extracted from the NRLMSISE00Atmosphere class

- [ ] Add the NRLMSISE input parameters as a dependent variable

This will allow the values that are used during the propagation to be retrieved, and allow the values used to be modified before the propagation

**Comment by DominicDirkx** [comment]
A little late, but finally implemented:

https://github.com/tudat-team/tudatpy/tree/feature/nrlmsiseOutput
https://github.com/tudat-team/tudat/tree/feature/nrlmsise_output

We'll open a PR to run the CI and check if we didn't break anything.

**Comment by DominicDirkx** [comment]
Merged!
