### ISSUE TITLE
Implementing a Warning for rotation matrix from body fixed to inertial frame

### ISSUE THREAD

**Issue by cfortunylombra** [tudat-team/tudat#44]
Hi everyone,

I just noticed that I get an identity matrix when I define a rotation matrix from body fixed to the inertial frame utilizing the `body_fixed_to_inertial_frame` attribute from the [feature/estimation_updates branch](https://github.com/tudat-team/tudatpy/blob/9055916643603cc2680f68eda4f6f078b967c973/tudatpy/kernel/expose_numerical_simulation/expose_environment.cpp#L493). I understood that the problem is that I should add the time in order to obtain the specific rotation matrix. However, it would be beneficial that a **warning** is popped out when I write the following example without a specific time:
```
rotation_from_Earth_body_frame_to_inertial_frame = bodies.get_body("Earth").body_fixed_to_inertial_frame
```

Hopefully, with this implementation, students will not fall into the trap by thinking that the rotation matrix is defined correctly. 

Thank you in advance. 

Greetings,
Carlos

**Comment by DominicDirkx** [comment]
This issue is addressed here:

https://github.com/tudat-team/tudat/tree/feature/improved_error_output

along with some other improved error output

**Comment by DominicDirkx** [comment]
Code merged
