### ISSUE TITLE
Add a banner on tudat.tudelft.nl to state that website is outdated

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#46]
If a user lands on [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html) anywhere different than the landing page, they will not see the warning to redirect to [tudat-space.readthedocs.io](https://tudat-space.readthedocs.io/en/latest/).

A banner can be added at the top of every page to fix this.

**Comment by gaffarelj** [comment]
@FilippoOggionni can you take care of this? If you don't have time, could you then point me to where the doc of [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html) are hosted and built, so I can update it myself?

**Comment by DominicDirkx** [comment]
The source should be pushed here:
https://github.com/tudat/tudat/tree/source

The sphinx docs should be built locally and pushed here
https://github.com/tudat/tudat/tree/gh-pages

**Comment by gaffarelj** [comment]
The theme we use on [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html) does not allow to simply setup an `annoucement` website-wide, like we can for [tudatpy.readthedocs.io](https://tudatpy.readthedocs.io/en/latest/index.html).
I thus added some Jquery in the template so that a header is injected at the top of each page. I also associated some CSS to make this fit the design, but be easily seen.

I will push all this when I am allowed to in the appropriate repositories (cfr [project management issue 23](https://github.com/tudat-team/project-management/issues/23)).

It should all result in the following:
![image](https://user-images.githubusercontent.com/50528981/150575407-da718896-d939-4d4e-a32d-813ee4ab3713.png)

**Comment by FilippoOggionni** [comment]
Thanks for taking care of this 🙌

**Comment by DominicDirkx** [comment]
This is great, thanks!

**Comment by gaffarelj** [comment]
Thank you for the invite.
When I try to push, I get the error that I do not have permission to push to `Tudat/tudat`. Perhaps me being part of the Tudat organization is not sufficient to grant me rights to push in that repo?

**Comment by DominicDirkx** [comment]
I explicitly added you to tudat/tudat. Hopefully that will do it :)

**Comment by gaffarelj** [comment]
Thank you, it's now working perfectly :)

**Comment by gaffarelj** [comment]
The banner has been added to the source with [94f5cfb](https://github.com/Tudat/tudat/commit/94f5cfbf28be8700c4c312f8c9717bc6e8a87551), and I published the new version of [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html) with [4510b0b](https://github.com/Tudat/tudat/commit/4510b0b0bc3b7b031602a44c67af6b0e62a842eb).

Note that, when visiting [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html), you may need to clear your cache (or refresh a couple of times) before the new content/style is loaded.

**Comment by gaffarelj** [comment]
The banner has been added to the source with [94f5cfb](https://github.com/Tudat/tudat/commit/94f5cfbf28be8700c4c312f8c9717bc6e8a87551), and I published the new version of [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html) with [4510b0b](https://github.com/Tudat/tudat/commit/4510b0b0bc3b7b031602a44c67af6b0e62a842eb).

Note that, when visiting [tudat.tudelft.nl](http://tudat.tudelft.nl/index.html), you may need to clear your cache (or refresh a couple of times) before the new content/style is loaded.
