### ISSUE TITLE
Bug when defining the viability settings are added to the simulation settings

### ISSUE THREAD

**Issue by cfortunylombra** [tudat-team/tudat#54]
Hi all,

I found out that the `addViabilityToObservationSimulationSettings(measurementSimulationInput,observationViabilitySettings);` does not work properly. This is because the number of observations is not reduced when viability requirements are defined and added to the simulation settings. Hence, this makes me understand that the simulation is performed without taking into account the viability settings. 

I noticed this when I was running this [code](https://github.com/cfortunylombra/PRIDE-Doppler-LaRa/blob/main/src/ValerioCodeTudat/LaRa_POD/LaRa_POD.cpp). Here, you can find an example of how it is defined.

Thank you in advance.

Greetings,
Carlos

**Comment by DominicDirkx** [comment]
Fix pushed to develop. Thanks for pointing this out
