### ISSUE TITLE
Could not find boost while creating Tudat application from CMakeLists.txt example

### ISSUE THREAD

**Issue by piofel** [tudat-team/tudat#55]
Hello,

I need to create a C++ Tudat app, using CMake, on Ubuntu 20.04. When I run `CMake: Configure` in Visual Studio Code on the example Tudat `CMakeLists.txt`, i.e., https://github.com/Tudat/tudatExampleApplications/blob/master/templateApplication/TemplateApplication/CMakeLists.txt, I receive the following error:
```
[cmake] CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
[cmake]   Could NOT find Boost (missing: Boost_INCLUDE_DIR thread date_time system
[cmake]   unit_test_framework filesystem regex) (Required is at least version
[cmake]   "1.45.0")
[cmake] Call Stack (most recent call first):
[cmake]   /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
[cmake]   /usr/share/cmake-3.16/Modules/FindBoost.cmake:2179 (find_package_handle_standard_args)
[cmake]   CMakeLists.txt:99 (find_package)
[cmake] 
[cmake] 
[cmake] CMake Warning (dev) in /usr/share/cmake-3.16/Modules/FindBoost.cmake:
[cmake]   Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
[cmake]   and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
[cmake]   cmake_policy command to set the policy and suppress this warning.
[cmake] 
[cmake]   The included script
[cmake] 
[cmake]     /usr/share/cmake-3.16/Modules/FindBoost.cmake
[cmake] 
[cmake]   affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
[cmake]   compatibility, so the effects are applied to the including context.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:99 (find_package)
[cmake] This warning is for project developers.  Use -Wno-dev to suppress it.
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "/home/piotr/pg/st/sat/aocs_design_suite_2/build/CMakeFiles/CMakeOutput.log".
[cmake] See also "/home/piotr/pg/st/sat/aocs_design_suite_2/build/CMakeFiles/CMakeError.log".
```
despite that I have installed the Boost components, i.e., `thread`, `date_time`, `system`, `test`, `filesystem` and `regex` in version `1.71.0`.

It may be relevant that I have installed Tudat using a `.yaml` file:
```
name: tudat-test
channels:
  - conda-forge
  - tudat-team
dependencies:
  - tudat
  - matplotlib
  - scipy
  - pandas
  ```
as recommended in https://github.com/tudat-team/tudat/issues/51

**Comment by DominicDirkx** [comment]
Hi Piotr, the template application (and anything else) from https://github.com/tudat is no longer compatible with the new version. There are two options:

* Create a CMakeLists.txt yourself for your application, using the tudat libraries in the conda package
* Add your application into the examples directory of the tudat-bundle/tudat directory when compiling from source, and enabling the associated CMakeLists for the example (which are currently commented out)

**Comment by piofel** [comment]
On Ubuntu, the problem with boost can be solved by `sudo apt-get install libboost-all-dev` (earlier I had installed only the selected components, what is not sufficient).

**Comment by DominicDirkx** [comment]
As an alternative, you could use the boost installation from your conda environment (see #51)
