### ISSUE TITLE
Feature Request: addDependentVariableToPropagatorSettings

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat#61]
Requesting a feature `addDependentVariableToPropagatorSettings`, which allows the user to add a (list of) `SingleDependentVariableSaveSettings` to an existing `PropagatorSettings` object. 

(Analogous to the existing `addDependentVariablesToObservationSimulationSettings` function for observation simulation settings.)

**Comment by jo11he** [comment]
The functionality has successfully been implemented in my forked repositories. 

tudat: https://github.com/jo11he/tudat/blob/94dde33dc4602988daeb8dc6c97e8865e727e4ef/include/tudat/simulation/propagation_setup/propagationSettings.h#L2218

tudatpy:
https://github.com/jo11he/tudatpy/blob/268323ee4191eeaca915235200b87978ec55d008/tudatpy/kernel/expose_numerical_simulation/expose_propagation_setup/expose_propagator_setup.cpp#L453

A pull request may not be the right way to go, since there may be other, untracked modifications in my forked branches (but we can try of course).
Alternatively I suggest to just copy paste the two paragraphs above (I can do that once I have your ok @DominicDirkx)
Is there a need for adding this in unit tests (I would not be capable of doing that)?

**Comment by DominicDirkx** [comment]
A unit test for this would be good, but it can be very short (check if setting 'normally' and like this results in the same output). Also, this function should have a multidoc entry. Hopefully I can get these implemented next week.

**Comment by DominicDirkx** [comment]
Code and unit test added here to address this issue:
https://github.com/tudat-team/tudat/tree/feature/po_updates
https://github.com/tudat-team/tudatpy/tree/feature/po_updates

**Comment by DominicDirkx** [comment]
Merged into develop (tudat/tudatpy) and main (tudat-multidoc)
