### ISSUE TITLE
Unit test: termination_condition_bug_fix

### ISSUE THREAD

**Issue by jo11he** [tudat-team/tudat#78]
Issue with how how the dynamics simulator and variational equations handle various post-processing issues - shown in  integration_completed_successfully checks after each integration of EoMs in estimation application.

Checking the `od_manager.variational_solver.dynamics_simulator` after having used the `od_manager` object in the simulation of observations

> estimation.simulate_observations(
>             observation_simulation_settings,
>             my_od_manager.observation_simulators,
>             bodies)

The integration_completed_successfully check fails here, with the following details:
terminated_on_exact_condition = 1
termination_reason = _propagation_never_run_

Quick-fix in https://github.com/tudat-team/tudat/tree/feature/termination_condition_bug_fix, unit test still open.

**Comment by DominicDirkx** [comment]
A fix to this has been pushed, with test.

This issue:

terminated_on_exact_condition = 1
termination_reason = propagation_never_run

comes from the `terminated_on_exact_condition` being meaningless if propagation_never_run. This should be improved in the docs (I'll leave this issue open for this).

**Comment by DominicDirkx** [comment]
Clarification in docs, and different default value for terminated_on_exact_condition (0) has been pushed.
