### ISSUE TITLE
Integrators refactoring

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#80]
We currently advise users to use `RungeKuttaVariableStepSizeIntegrator` with a tolerance of `inf` if they wish to use high-order RK methods with a fixed step. Doing so, the `RungeKuttaVariableStepSizeIntegrator` still tries to compute the optimum step size.
I suggest two improvements.

First (and the easiest) is to detect when the tolerance is `inf` in `RungeKuttaVariableStepSizeIntegrator`, and to simply return the minimum step size in this case in the `computeNextStepSizeAndValidateResult` and `computeNewStepSize`. This would bypass useless computations (and avoid potential error if the step size computation goes to infinite values, see issue #77 for instance).

Second, we could add a new `RungeKuttaIntegrator` that, does fixed-step integrations, much like the `RungeKutta4Integrator`. The user would then only have to specify the initial epoch, the coefficient set, and the step size. In this setup, we could actually remove the `RungeKutta4Integrator`, as the user could now use the new `RungeKuttaIntegrator` and specify the coefficient set for this to become RK4. But removing `RungeKutta4Integrator` would break backward compatibility (we can simply remove it from the doc and/or the Python exposition).

@DominicDirkx also mentioned another improvement to make variable step size computation more efficient:
*I propose adding new integrator options, where instead of evaluating all stages of (for instance) the RKF7(8), we evaluate only the stages needed for the 7th or 8th order one.*

**Comment by gaffarelj** [comment]
Update: the first thing to be implemented in this integrator refactoring is to make the fixed-step Euler and RK4 integrators use a new more general fixed-step integrator with Butcher tableau as input (#81).

**Comment by gaffarelj** [comment]
The next step in this refactoring, after the new fixed-step integrator is implemented, could be the custom-step integrator described in #87.

**Comment by gaffarelj** [comment]
Details on what is to be done to refactor the variable step size integrator (especially step size control) is given in #92.

**Comment by DominicDirkx** [comment]
All remaining tasks are tracked in other issues, closing this one
