### ISSUE TITLE
Maximum Elevation Angle Viability

### ISSUE THREAD

**Issue by cfortunylombra** [tudat-team/tudat#82]
Hi all,

Since `tudat` does not have a viability setting for a maximum elevation angle, I have made some changes in a couple of files. These files are attached to this GitHub issue ([observationViabilityCalculator.cpp](https://github.com/tudat-team/tudat/blob/3bf584522c4715f0aae4d6dee54063738ed592d8/src/astro/observation_models/observationViabilityCalculator.cpp); [observationViabilityCalculator.h](https://github.com/tudat-team/tudat/blob/3bf584522c4715f0aae4d6dee54063738ed592d8/include/tudat/astro/observation_models/observationViabilityCalculator.h); [createObservationViability.cpp](https://github.com/tudat-team/tudat/blob/3bf584522c4715f0aae4d6dee54063738ed592d8/src/simulation/estimation_setup/createObservationViability.cpp); [createObservationViability.h](https://github.com/tudat-team/tudat/blob/3bf584522c4715f0aae4d6dee54063738ed592d8/include/tudat/simulation/estimation_setup/createObservationViability.h); [expose_observation_setup.cpp](https://github.com/tudat-team/tudatpy/blob/37a3b33a7c3e15b23bc454d8953b5503d011db6c/tudatpy/kernel/expose_numerical_simulation/expose_estimation_setup/expose_observation_setup.cpp)). What I have done is basically copy and paste the definitions of the minimum elevation angle. 

The changes made can also be shortened by inserting a boolean in the definition of `isObservationViable` [function ](https://github.com/tudat-team/tudat/blob/3bf584522c4715f0aae4d6dee54063738ed592d8/src/astro/observation_models/observationViabilityCalculator.cpp#L54) (in observationViabilityCalculator.cpp). I tried to do this approach, but it did not work out for me.

To make sure that the function was written correctly, the[ unitTestObservationViabilityCalculators.cpp](https://github.com/tudat-team/tudat/blob/3bf584522c4715f0aae4d6dee54063738ed592d8/tests/src/astro/observation_models/unitTestObservationViabilityCalculators.cpp) has been updated as well (the test did not not failed).

Greetings, 
Carlos

Attachments: 
[ElevationAngleViability.zip](https://github.com/tudat-team/tudat/files/8408707/ElevationAngleViability.zip)

**Comment by DominicDirkx** [comment]
The pull request for this is open; closing issue
