### ISSUE TITLE
Request: propagate variational dynamics at the same time as mass state

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#84]
It is currently not possible to propagate variational dynamics when the mass of the body is propagated at the same time as its translational state. Errors like these are raised instead:
```
RuntimeError: Warning, dependency of central gravity on body masses not yet implemented
RuntimeError: Warning, dependency of aerodynamic acceleration on body masses not yet implemented
```

In particular, a (somewhat tricky) link to thrust acceleration must be made.

This feature request is low-priority.

**Comment by DominicDirkx** [comment]
This has been addressed and added in the thrust/rotation refactor, I've just pushed an improvement to the unit test of this to the develop branch.
