### ISSUE TITLE
Error checking for empty body settings

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#85]
Hi all,

Apparently it is possible to create a body with empty settings, which eventually causes the code crashes when creating the dynamics simulator... so somewhere it should be checked whether a given body has empty settings, and an error thrown if so.

Code triggering the issue is attached: empty body settings created in line 78, code crashes in line 290.

Assigned the issue to Jérémie... but not completely sure whether you're the responsible person

[test_tudat_bundle.py.zip](https://github.com/tudat-team/tudat/files/8479717/test_tudat_bundle.py.zip)

**Comment by gaffarelj** [comment]
Hi Miguel,

Thanks for raising this issue, and especially for attaching code with it. I will take care of it when possible, probably this week.

**Comment by DominicDirkx** [comment]
Hi Miguel, Jeremie, I'd like to have a look a what's going on here, because it *should* be possible to do this. Apparently, some check is missing that a certain member of the empty body (?) is accessed. Will have a look at it and post a proposed solution

**Comment by DominicDirkx** [comment]
Running an equivalent C++ program with the GNU debugger (gdb) indicated that the crash was here:

https://github.com/tudat-team/tudat/blob/2afa3f00f3c1511efeb33e18551121ec1f660f87/src/simulation/propagation_setup/setNumericallyIntegratedStates.cpp#L24

when propagating dynamics, and a non-propagated body without an ephemeris was in the environment, a segmentation fault occured. This has now been corrected by the latest push to develop.
