### ISSUE TITLE
Code compiled in debug mode crashes when calling integrate_equations_of_motion

### ISSUE THREAD

**Issue by MiguelAvillez** [tudat-team/tudat#86]
Hi all,

When using a tudatpy kernel compiled in debug mode the code crashes when calling the integrate_equations_of_motion function (see code attached, it crashes in line 304). The code works without any issue when using a kernel compiled in release mode.

[test_tudat_bundle.py.zip](https://github.com/tudat-team/tudat/files/8488686/test_tudat_bundle.py.zip)

**Comment by DominicDirkx** [comment]
I'm building tudat in debug mode now, and will run an application that does this. After compiling in debug mode, you did run all the unit tests right?

**Comment by MiguelAvillez** [comment]
Yes, I did, all tests passed. It takes very very long to run the tests though
