### ISSUE TITLE
New custom step size control for variable step integrator

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#87]
Currently, the variable step-size integrator automatically computes the optimum step size based on tolerances that were set by the user, and the estimated error thanks to computing a higher and lower order.

A different method should be added, that computes only one of the orders but calls a user-defined function to know what time step to take.
In essence, this method would be similar to the new rungeKuttaFixedStepSizeIntegrator, except that the `getNextStepSize()` function would link to the user-defined function, instead of always returning the pre-defined `stepSize_`.

I am not too familiar with overloading, but I assume that, on the C++ side, the rungeKuttaFixedStepSizeIntegrator class could just be adapted so that it accepts either a float or a function for the stepsize. On the Python side, we would expose these two overloads separately, so that we have `runge_kutta_fixed_step_size` and `runge_kutta_custom_step_size` (or something similar).

**Comment by DominicDirkx** [comment]
Resolution of issue will be tracked here: https://github.com/tudat-team/tudat/issues/166
