### ISSUE TITLE
Feature request: keep state history only every N seconds

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#89]
When a propagation makes a considerable number of function evaluations (> 10^9 for instance), the state vector history can become so big that hundreds of Go of RAM become necessary to keep it.
However, in some cases, all of this state history is not necessary.

A new feature ould be added so that, at a fixed number of steps or time interval, the state history of the previous interval gets interpolated, and the interpolated history is saved, freeing the memory of the full state history.

I can already see some issues to make sure that we do not simply introduce interpolation artifacts everywhere, but this would allow users to run more precise simulations without running out of memory on a laptop, or overkill precise simulations without running out of memory on a server.

**Comment by DominicDirkx** [comment]
This is sort of what the save_frequency input here:

https://py.api.tudat.space/en/latest/integrator.html#tudatpy.numerical_simulation.propagation_setup.integrator.runge_kutta_4

does. It only saves the state/dependent variables once every save_frequency steps. A few problems:

* Putting this in the integrator settings is weird
* It does not allow you to get output every N seconds, only every M steps (which is fine for fixed-steps, but a nuisance for variable steps)

We could tackle this issue in the short term, but I propose we make it a part of the (hopefully) near future revision of the propagator/integrator settings. For this, there are couple of ideas:

* The integrator settings will become part of the propagator settings
* A single comprehensive output settings input will be created
* A single object containing all the output (state, dependent variables, succesful propagation, termination reason, etc.) will be created

Your proposed modification would fit perfectly

**Comment by DominicDirkx** [comment]
Merged into develop from #137
