### ISSUE TITLE
Linux build failing with boost 1.70+

### ISSUE THREAD

**Issue by ggarrett13** [tudat-team/tudat#9]
Likely to do with `_GLIBCXX_USE_CXX11_ABI` and the boost build supplied on anaconda.org.
- [1.70 Azure log](https://dev.azure.com/tudat-team/feedstock-builds/_build/results?buildId=167&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14)
- [1.71 Azure log](https://dev.azure.com/tudat-team/feedstock-builds/_build/results?buildId=167&view=logs&j=517fe804-fa30-5dc2-1413-330699242c05&t=c10fa5f2-fdf6-5338-3bdb-c4bea7c23412)

**Comment by DominicDirkx** [comment]
Fixed when incorporating pygmo
