### ISSUE TITLE
Depreciation warnings for orientation refactoring

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudat#98]
Depreciation warnings should be added to every current method that will be replaced by the new orientations interfaces that @DominicDirkx is working on.

These warnings should indicate the approximate time at which the methods will be depreciated, and what the future methods that replace that functionality are named.

It is also important to publish a last conda package containing this, and to save what version number it is (last before minor version increase), so that we can refer it to users.

@DominicDirkx can you link the methods that will be depraciated when you have some time?

**Comment by DominicDirkx** [comment]
Implemented since v2.11.0
